package in.capgemini.kanbantool.domain;



import java.util.Date;


/**
 * This Project modal is used to hold the data will travel layer to layer
 * @author hsraj
 *
 */
public class Project {
@Override
	public String toString() {
		return "Project [id=" + id + ", projectName=" + projectName + ", projectIdentifier=" + projectIdentifier
				+ ", description=" + description + "]";
	}
	/*
 * id of the project
 * autogenerated
 * */
	private int id;
	/*
	 * name of the project . It should be required
	 * */
	
	private String projectName;
	/*
	 * identifier of the project. It should be unique
	 * */
	private String projectIdentifier;
	/*
	 * description of the project
	 * description is required
	 * */
	private String description;
	/*
	 * start date of the project
	 * */
	private Date startDate;
	/*
	 * end date of the project
	 * */
	private Date endDate;
	/*
	 * date at which project is created
	 * */
	private Date createdAt;
	/*
	 *project at which project is updated
	 * */
	private Date updatedAt;
	
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getProjectName() {
		return projectName;
	}
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}
	public String getProjectIdentifier() {
		return projectIdentifier;
	}
	public void setProjectIdentifier(String projectIdentifier) {
		this.projectIdentifier = projectIdentifier;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Date getStartDate() {
		return startDate;
	}
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	public Date getEndDate() {
		return endDate;
	}
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	public Date getCreatedAt() {
		return createdAt;
	}
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	public Date getUpdatedAt() {
		return updatedAt;
	}
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
	
	
}
